export { default as AbstractDesign } from '../img/Abstract Design.svg'
export {default as webDesignImage} from '../../assets/img/web_design_fundamentals.svg'
export {default as  uiuxImage} from '../../assets/img/uiux_design.svg'
export {default as  mobileDevelopmentImage} from '../../assets/img/mobile_app_development.svg'
export {default as advanceJsImage} from '../../assets/img/advance_js.svg'
export {default as graphicDesignImage} from '../../assets/img/graphic_design_for_beginners.svg'
export {default as frontEndImage} from '../../assets/img/front_end_development.svg'
export {default as  AbstractIcon} from '../../assets/img/Abstract Line.svg'
export {default as videoImg} from '../../assets/img/video_img.svg'
export {default as logo} from '../../assets/img/Logo.svg'
export {default as uiux_design} from "../../assets/img/uiux_design.svg";
export {default as SarahImg} from '../../assets/img/Sarah L.svg'
export {default as backwardArrow} from '../../assets/img/backward_arrow.svg'
export {default as forwardArrow} from '../../assets/img/forward_arrow.svg'
export {default as loginArrow} from '../../assets/img/login_arrow.svg'
export {default as googleLogo} from '../../assets/img/google_logo.svg'
export {default as JasonImage} from '../../assets/img/jason_img.svg'
export {default as EmilyImage} from '../../assets/img/Emily R.svg'
export {default as MichaelImage} from '../../assets/img/michael_img.svg'
export {default as faqForwardButton} from "../../assets/img/faq_forward_button.svg"

